/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Conexion.Conexion;
import Conexion.ImagenFondo;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.omg.CORBA.portable.InputStream;

/**
 *
 * @author Ronni
 */
public class PrimeraInterface extends javax.swing.JFrame {

    /**
     * Creates new form PrimeraInterface
     */
    String codEncomiendaOficina;

    public PrimeraInterface(String codOficina, String[] nombre) {
        codEncomiendaOficina = codOficina;
        initComponents();
        txtUsuaio.setText(nombre[0] + " " + nombre[1]);

        this.setTitle("SKY WAY");
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/sk.png")).getImage());
        principal.setBorder(new ImagenFondo());
        this.setExtendedState(PrimeraInterface.MAXIMIZED_BOTH);
        principal.setBorder(new ImagenFondo());
        this.setExtendedState(PrimeraInterface.MAXIMIZED_BOTH);
        setExtendedState(MAXIMIZED_BOTH);
    }

    private void salir() {
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int op = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea salir?", "Advertencia", dialogButton);
        if (op == 0) {
            this.dispose();
        }
    }

    public static boolean ventanasAbiertas(Object ventana) {
        JInternalFrame[] activos = principal.getAllFrames();
        int i = 0;
        boolean cerrada = true;
        while (i < activos.length && cerrada) {
            if (activos[i] == ventana) {
              return false;
            } else {
               activos[i].doDefaultCloseAction();
            }
            i++;
        }
        return cerrada;
    }
    private void cerrarSesion() {
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int op = JOptionPane.showConfirmDialog(null, "¿Desea cerrar sesión actual?", "Advertencia", dialogButton);
        if (op == 0) {
            Login l = new Login();
            l.setVisible(true);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        principal = new javax.swing.JDesktopPane();
        reportes = new javax.swing.JPanel();
        Clientes = new javax.swing.JButton();
        Rutas = new javax.swing.JButton();
        Buses = new javax.swing.JButton();
        oficinas = new javax.swing.JButton();
        empleados = new javax.swing.JButton();
        reportes2 = new javax.swing.JPanel();
        Clientes1 = new javax.swing.JButton();
        Rutas1 = new javax.swing.JButton();
        reportes1 = new javax.swing.JPanel();
        Viajes = new javax.swing.JButton();
        Encomiendas = new javax.swing.JButton();
        Unidades = new javax.swing.JButton();
        Encomiendas2 = new javax.swing.JButton();
        Encomiendas3 = new javax.swing.JButton();
        Encomiendas5 = new javax.swing.JButton();
        Encomiendas6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        txtUsuaio = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        menuFacturacion1 = new javax.swing.JButton();
        fac1 = new javax.swing.JButton();
        usuario = new javax.swing.JPanel();
        fac3 = new javax.swing.JButton();
        fac4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        principal.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);
        principal.setPreferredSize(new java.awt.Dimension(771, 529));

        reportes.setBackground(new java.awt.Color(0, 0, 0));
        reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportesMouseExited(evt);
            }
        });
        reportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Clientes.setBackground(new java.awt.Color(0, 0, 0));
        Clientes.setForeground(new java.awt.Color(255, 255, 255));
        Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.png"))); // NOI18N
        Clientes.setText("Clientes");
        Clientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Clientes.setFocusable(false);
        Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClientesMouseExited(evt);
            }
        });
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        reportes.add(Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 138, 30));

        Rutas.setBackground(new java.awt.Color(0, 0, 0));
        Rutas.setForeground(new java.awt.Color(255, 255, 255));
        Rutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/rutas.png"))); // NOI18N
        Rutas.setText("Rutas");
        Rutas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Rutas.setFocusable(false);
        Rutas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RutasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RutasMouseExited(evt);
            }
        });
        Rutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutasActionPerformed(evt);
            }
        });
        reportes.add(Rutas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 138, 30));

        Buses.setBackground(new java.awt.Color(0, 0, 0));
        Buses.setForeground(new java.awt.Color(255, 255, 255));
        Buses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bus2.png"))); // NOI18N
        Buses.setText("Buses");
        Buses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buses.setFocusable(false);
        Buses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BusesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BusesMouseExited(evt);
            }
        });
        Buses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusesActionPerformed(evt);
            }
        });
        reportes.add(Buses, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 138, 30));

        oficinas.setBackground(new java.awt.Color(0, 0, 0));
        oficinas.setForeground(new java.awt.Color(255, 255, 255));
        oficinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/oficinas.png"))); // NOI18N
        oficinas.setText("Oficinas");
        oficinas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        oficinas.setFocusable(false);
        oficinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                oficinasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                oficinasMouseExited(evt);
            }
        });
        oficinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oficinasActionPerformed(evt);
            }
        });
        reportes.add(oficinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 138, 30));

        empleados.setBackground(new java.awt.Color(0, 0, 0));
        empleados.setForeground(new java.awt.Color(255, 255, 255));
        empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/account-tie.png"))); // NOI18N
        empleados.setText("Empleados");
        empleados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        empleados.setFocusable(false);
        empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                empleadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                empleadosMouseExited(evt);
            }
        });
        empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadosActionPerformed(evt);
            }
        });
        reportes.add(empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 138, 30));

        reportes2.setBackground(new java.awt.Color(0, 0, 0));
        reportes2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportes2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportes2MouseExited(evt);
            }
        });
        reportes2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Clientes1.setBackground(new java.awt.Color(0, 0, 0));
        Clientes1.setForeground(new java.awt.Color(255, 255, 255));
        Clientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmpleadoReg.png"))); // NOI18N
        Clientes1.setText("Ingreso Em");
        Clientes1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Clientes1.setFocusable(false);
        Clientes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Clientes1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Clientes1MouseExited(evt);
            }
        });
        Clientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clientes1ActionPerformed(evt);
            }
        });
        reportes2.add(Clientes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        Rutas1.setBackground(new java.awt.Color(0, 0, 0));
        Rutas1.setForeground(new java.awt.Color(255, 255, 255));
        Rutas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmpleadoTip.png"))); // NOI18N
        Rutas1.setText("Tipos Emp");
        Rutas1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Rutas1.setFocusable(false);
        Rutas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Rutas1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Rutas1MouseExited(evt);
            }
        });
        Rutas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rutas1ActionPerformed(evt);
            }
        });
        reportes2.add(Rutas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 130, 30));

        reportes1.setBackground(new java.awt.Color(0, 0, 0));
        reportes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportes1MouseEntered(evt);
            }
        });
        reportes1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Viajes.setBackground(new java.awt.Color(0, 0, 0));
        Viajes.setForeground(new java.awt.Color(255, 255, 255));
        Viajes.setText("Viajes");
        Viajes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Viajes.setFocusable(false);
        Viajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViajesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViajesMouseExited(evt);
            }
        });
        Viajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViajesActionPerformed(evt);
            }
        });
        reportes1.add(Viajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        Encomiendas.setBackground(new java.awt.Color(0, 0, 0));
        Encomiendas.setForeground(new java.awt.Color(255, 255, 255));
        Encomiendas.setText("Empleados");
        Encomiendas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Encomiendas.setFocusable(false);
        Encomiendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EncomiendasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EncomiendasMouseExited(evt);
            }
        });
        Encomiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncomiendasActionPerformed(evt);
            }
        });
        reportes1.add(Encomiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 110, 20));

        Unidades.setBackground(new java.awt.Color(0, 0, 0));
        Unidades.setForeground(new java.awt.Color(255, 255, 255));
        Unidades.setText("Unidades");
        Unidades.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Unidades.setFocusable(false);
        Unidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UnidadesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UnidadesMouseExited(evt);
            }
        });
        Unidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnidadesActionPerformed(evt);
            }
        });
        reportes1.add(Unidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 110, 20));

        Encomiendas2.setBackground(new java.awt.Color(0, 0, 0));
        Encomiendas2.setForeground(new java.awt.Color(255, 255, 255));
        Encomiendas2.setText("Oficinas");
        Encomiendas2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Encomiendas2.setFocusable(false);
        Encomiendas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Encomiendas2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Encomiendas2MouseExited(evt);
            }
        });
        Encomiendas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Encomiendas2ActionPerformed(evt);
            }
        });
        reportes1.add(Encomiendas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 110, 20));

        Encomiendas3.setBackground(new java.awt.Color(0, 0, 0));
        Encomiendas3.setForeground(new java.awt.Color(255, 255, 255));
        Encomiendas3.setText("Rutas");
        Encomiendas3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Encomiendas3.setFocusable(false);
        Encomiendas3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Encomiendas3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Encomiendas3MouseExited(evt);
            }
        });
        Encomiendas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Encomiendas3ActionPerformed(evt);
            }
        });
        reportes1.add(Encomiendas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 110, 20));

        Encomiendas5.setBackground(new java.awt.Color(0, 0, 0));
        Encomiendas5.setForeground(new java.awt.Color(255, 255, 255));
        Encomiendas5.setText("Varios");
        Encomiendas5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Encomiendas5.setFocusable(false);
        Encomiendas5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Encomiendas5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Encomiendas5MouseExited(evt);
            }
        });
        Encomiendas5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Encomiendas5ActionPerformed(evt);
            }
        });
        reportes1.add(Encomiendas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 110, 20));

        Encomiendas6.setBackground(new java.awt.Color(0, 0, 0));
        Encomiendas6.setForeground(new java.awt.Color(255, 255, 255));
        Encomiendas6.setText("Encomiendas");
        Encomiendas6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Encomiendas6.setFocusable(false);
        Encomiendas6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Encomiendas6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Encomiendas6MouseExited(evt);
            }
        });
        Encomiendas6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Encomiendas6ActionPerformed(evt);
            }
        });
        reportes1.add(Encomiendas6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 110, 20));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clipboard-text.png"))); // NOI18N
        jButton6.setText("Reportes");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.setFocusable(false);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        txtUsuaio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUsuaio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/account-circle.png"))); // NOI18N

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder-edit.png"))); // NOI18N
        jButton9.setText("Editar");
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.setFocusable(false);
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton9MouseExited(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        menuFacturacion1.setBackground(new java.awt.Color(0, 153, 255));
        menuFacturacion1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        menuFacturacion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arrow-down-drop-circle-outline.png"))); // NOI18N
        menuFacturacion1.setToolTipText("");
        menuFacturacion1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuFacturacion1.setFocusable(false);
        menuFacturacion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuFacturacion1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuFacturacion1MouseExited(evt);
            }
        });
        menuFacturacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFacturacion1ActionPerformed(evt);
            }
        });

        fac1.setBackground(new java.awt.Color(0, 0, 0));
        fac1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        fac1.setForeground(new java.awt.Color(255, 255, 255));
        fac1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/viajes.png"))); // NOI18N
        fac1.setText("Viajes");
        fac1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fac1.setFocusable(false);
        fac1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fac1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fac1MouseExited(evt);
            }
        });
        fac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fac1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(fac1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(txtUsuaio, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuFacturacion1)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton6)
                .addComponent(jButton9)
                .addComponent(fac1))
            .addComponent(txtUsuaio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuFacturacion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        usuario.setBackground(new java.awt.Color(0, 153, 255));
        usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usuarioMouseEntered(evt);
            }
        });
        usuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fac3.setBackground(new java.awt.Color(0, 153, 255));
        fac3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/account-edit.png"))); // NOI18N
        fac3.setText("Configuraciónes");
        fac3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fac3.setFocusable(false);
        fac3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fac3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fac3MouseExited(evt);
            }
        });
        fac3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fac3ActionPerformed(evt);
            }
        });
        usuario.add(fac3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        fac4.setBackground(new java.awt.Color(0, 153, 255));
        fac4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        fac4.setText("Cerrar Sesión");
        fac4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fac4.setFocusable(false);
        fac4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fac4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fac4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fac4MouseExited(evt);
            }
        });
        fac4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fac4ActionPerformed(evt);
            }
        });
        usuario.add(fac4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 130, 30));

        principal.setLayer(reportes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        principal.setLayer(reportes2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        principal.setLayer(reportes1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        principal.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        principal.setLayer(usuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(principalLayout.createSequentialGroup()
                .addComponent(reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalLayout.createSequentialGroup()
                        .addComponent(reportes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(principalLayout.createSequentialGroup()
                        .addComponent(reportes2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(reportes1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(reportes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 1314, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        // TODO add your handling code here:
        jButton6.setToolTipText("Reportes existentes");
        reportes1.setSize(110, 140);
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        // TODO add your handling code here:
        reportes1.setSize(0, 0);
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseEntered
        // TODO add your handling code here:
        jButton6.setToolTipText("Reportes existentes");
        reportes.setSize(138, 150);
    }//GEN-LAST:event_jButton9MouseEntered

    private void jButton9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseExited
        // TODO add your handling code here:
        reportes.setSize(0, 0);
    }//GEN-LAST:event_jButton9MouseExited

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void ClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesMouseEntered
        // TODO add your handling code here:
        Clientes.setToolTipText("Detalle de averias");
        reportes.setSize(138, 150);
    }//GEN-LAST:event_ClientesMouseEntered

    private void ClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesMouseExited
        // TODO add your handling code here:
        reportes.setSize(0, 0);
    }//GEN-LAST:event_ClientesMouseExited

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed

        IngresoClientes c = null;
         if (ventanasAbiertas(c)) {
        try {
            c = new IngresoClientes();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PrimeraInterface.class.getName()).log(Level.SEVERE, null, ex);
        }

        principal.add(c);
        Dimension desktopSize = principal.getSize();
        Dimension internalSize = c.getSize();
        c.setLocation((desktopSize.width - internalSize.width) / 2, (desktopSize.height - internalSize.height) / 2);
        c.setVisible(true);
         }
    }//GEN-LAST:event_ClientesActionPerformed

    private void RutasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RutasMouseEntered
        // TODO add your handling code here:
        reportes.setSize(138, 150);
        Rutas.setToolTipText("Detalle de repuestos");
    }//GEN-LAST:event_RutasMouseEntered

    private void RutasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RutasMouseExited
        // TODO add your handling code here:
        reportes.setSize(0, 0);
    }//GEN-LAST:event_RutasMouseExited

    private void RutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutasActionPerformed
        // TODO add your handling code here:
        Rutas r = null;
         if (ventanasAbiertas(r)) {
        r=new Rutas();
        principal.add(r);
        Dimension desktopSize = principal.getSize();
        Dimension internalSize = r.getSize();
        r.setLocation((desktopSize.width - internalSize.width) / 2, (desktopSize.height - internalSize.height) / 2);
        r.setVisible(true);
         }
    }//GEN-LAST:event_RutasActionPerformed

    private void reportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_reportesMouseEntered

    private void ViajesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViajesMouseEntered
        // TODO add your handling code here:
        Clientes.setToolTipText("Detalle de averias");
        reportes1.setSize(110, 140);
    }//GEN-LAST:event_ViajesMouseEntered

    private void ViajesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViajesMouseExited
        // TODO add your handling code here:
        reportes1.setSize(0, 0);
    }//GEN-LAST:event_ViajesMouseExited

    private void ViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViajesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ViajesActionPerformed

    private void EncomiendasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncomiendasMouseEntered
        // TODO add your handling code here:
        Clientes.setToolTipText("Detalle de averias");
        reportes1.setSize(110, 140);
    }//GEN-LAST:event_EncomiendasMouseEntered

    private void EncomiendasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncomiendasMouseExited
        // TODO add your handling code here:
        reportes1.setSize(0, 0);
    }//GEN-LAST:event_EncomiendasMouseExited

    private void EncomiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncomiendasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_EncomiendasActionPerformed

    private void UnidadesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UnidadesMouseEntered
        // TODO add your handling code here:
        Clientes.setToolTipText("Detalle de averias");
        reportes1.setSize(110, 140);
    }//GEN-LAST:event_UnidadesMouseEntered

    private void UnidadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UnidadesMouseExited
        // TODO add your handling code here:
        reportes1.setSize(0, 0);
    }//GEN-LAST:event_UnidadesMouseExited

    private void UnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnidadesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_UnidadesActionPerformed

    private void reportes1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportes1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_reportes1MouseEntered

    private void BusesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BusesMouseEntered
        // TODO add your handling code here:
        reportes.setSize(138, 150);
        Rutas.setToolTipText("Detalle de repuestos");
    }//GEN-LAST:event_BusesMouseEntered

    private void BusesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BusesMouseExited
        // TODO add your handling code here:
        reportes.setSize(0, 0);

    }//GEN-LAST:event_BusesMouseExited

    private void BusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusesActionPerformed
        // TODO add your handling code here:
        IngresoBus ib = null;
        if (ventanasAbiertas(ib)) {
            ib= new IngresoBus();
        principal.add(ib);
        Dimension desktopSize = principal.getSize();
        Dimension internalSize = ib.getSize();
        ib.setLocation((desktopSize.width - internalSize.width) / 2, (desktopSize.height - internalSize.height) / 2);
        ib.setVisible(true);
         }
    }//GEN-LAST:event_BusesActionPerformed

    private void empleadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empleadosMouseEntered
        // TODO add your handling code here:
        reportes.setSize(138, 150);
        reportes2.setSize(130, 60);
        Rutas.setToolTipText("Detalle de repuestos");
    }//GEN-LAST:event_empleadosMouseEntered

    private void empleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empleadosMouseExited
        // TODO add your handling code here:
        reportes.setSize(0, 0);
        reportes2.setSize(0, 0);
    }//GEN-LAST:event_empleadosMouseExited

    private void empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_empleadosActionPerformed

    private void oficinasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oficinasMouseEntered
        // TODO add your handling code here:
        reportes.setSize(138, 150);
        Rutas.setToolTipText("Detalle de repuestos");
    }//GEN-LAST:event_oficinasMouseEntered

    private void oficinasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oficinasMouseExited
        // TODO add your handling code here:
        reportes.setSize(0, 0);

    }//GEN-LAST:event_oficinasMouseExited

    private void oficinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oficinasActionPerformed
        // TODO add your handling code here:
        IngresoOficinas o =null;
        if (ventanasAbiertas(o)) {
            o= new IngresoOficinas();
        principal.add(o);
        Dimension desktopSize = principal.getSize();
        Dimension internalSize = o.getSize();
        o.setLocation((desktopSize.width - internalSize.width) / 2, (desktopSize.height - internalSize.height) / 2);
        o.setVisible(true);
        }
    }//GEN-LAST:event_oficinasActionPerformed

    private void Encomiendas2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Encomiendas2MouseEntered
        // TODO add your handling code here:
        Clientes.setToolTipText("Detalle de averias");
        reportes1.setSize(110, 140);
    }//GEN-LAST:event_Encomiendas2MouseEntered

    private void Encomiendas2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Encomiendas2MouseExited
        // TODO add your handling code here:
        reportes1.setSize(0, 0);
    }//GEN-LAST:event_Encomiendas2MouseExited

    private void Encomiendas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Encomiendas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Encomiendas2ActionPerformed

    private void Encomiendas3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Encomiendas3MouseEntered
        // TODO add your handling code here:
        Clientes.setToolTipText("Detalle de averias");
        reportes1.setSize(110, 140);
    }//GEN-LAST:event_Encomiendas3MouseEntered

    private void Encomiendas3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Encomiendas3MouseExited
        // TODO add your handling code here:
        reportes1.setSize(0, 0);
    }//GEN-LAST:event_Encomiendas3MouseExited

    private void Encomiendas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Encomiendas3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Encomiendas3ActionPerformed

    private void Encomiendas5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Encomiendas5MouseEntered
        // TODO add your handling code here:
        Clientes.setToolTipText("Detalle de averias");
        reportes1.setSize(110, 140);
    }//GEN-LAST:event_Encomiendas5MouseEntered

    private void Encomiendas5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Encomiendas5MouseExited
        // TODO add your handling code here:
        reportes1.setSize(0, 0);
    }//GEN-LAST:event_Encomiendas5MouseExited

    private void Encomiendas5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Encomiendas5ActionPerformed
        // TODO add your handling code here:
        parametros p = null;
        if (ventanasAbiertas(p)) {
            p = new parametros();
            principal.add(p);
            Dimension desktopSize = principal.getSize();
            Dimension internalSize = p.getSize();
            p.setLocation((desktopSize.width - internalSize.width) / 2, (desktopSize.height - internalSize.height) / 2);
            p.setVisible(true);
        }
    }//GEN-LAST:event_Encomiendas5ActionPerformed

    private void Encomiendas6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Encomiendas6MouseEntered
        // TODO add your handling code here:
        Clientes.setToolTipText("Detalle de averias");
        reportes1.setSize(110, 140);
    }//GEN-LAST:event_Encomiendas6MouseEntered

    private void Encomiendas6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Encomiendas6MouseExited
        // TODO add your handling code here:
        reportes1.setSize(0, 0);
    }//GEN-LAST:event_Encomiendas6MouseExited

    private void Encomiendas6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Encomiendas6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Encomiendas6ActionPerformed

    private void fac1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fac1MouseEntered
        // TODO add your handling code here:
        Clientes.setToolTipText("Detalle de averias");
    }//GEN-LAST:event_fac1MouseEntered

    private void fac1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fac1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_fac1MouseExited

    private String cedulaEmpleado(String codOficina) {
        String cedula = "";
        try {
            Conexion cc = new Conexion();
            Connection cn = cc.conexion();
            String sql = "SELECT CED_PERSONAL_PER "
                    + "FROM PERSONAL_OFICINA "
                    + "WHERE COD_OFI_PER = '" + codOficina + "'";
            Statement psd = cn.createStatement();
            ResultSet rs = psd.executeQuery(sql);

            while (rs.next()) {
                cedula = rs.getString("CED_PERSONAL_PER");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

        return cedula;
    }

    private void fac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fac1ActionPerformed
        // TODO add your handling code here:
        String ced = cedulaEmpleado(codEncomiendaOficina);
        IngresoViajesbus iv = null;
        if (ventanasAbiertas(iv)) {
            iv = new IngresoViajesbus(Login.usuario.getText());
            principal.add(iv);
            Dimension desktopSize = principal.getSize();
            Dimension internalSize = iv.getSize();
            iv.setLocation((desktopSize.width - internalSize.width) / 2, (desktopSize.height - internalSize.height) / 2);
            iv.setVisible(true);
        }
    }//GEN-LAST:event_fac1ActionPerformed

    private void reportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_reportesMouseExited

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_formWindowClosing

    private void Clientes1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clientes1MouseEntered
        // TODO add your handling code here:
        reportes.setSize(138, 150);
        reportes2.setSize(130, 60);
    }//GEN-LAST:event_Clientes1MouseEntered

    private void Clientes1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clientes1MouseExited
        // TODO add your handling code here:
        reportes.setSize(0, 0);
        reportes2.setSize(0, 0);
    }//GEN-LAST:event_Clientes1MouseExited


    private void Clientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clientes1ActionPerformed
        // TODO add your handling code here:

        IngresoEmpleado ie = null;
        if (ventanasAbiertas(ie)) {
            ie = new IngresoEmpleado();
            principal.add(ie);
            Dimension desktopSize = principal.getSize();
            Dimension internalSize = ie.getSize();
            ie.setLocation((desktopSize.width - internalSize.width) / 2, (desktopSize.height - internalSize.height) / 2);
            ie.setVisible(true);
        }
    }//GEN-LAST:event_Clientes1ActionPerformed

    private void Rutas1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rutas1MouseEntered
        // TODO add your handling code here:
        reportes.setSize(138, 150);
        reportes2.setSize(130, 60);
    }//GEN-LAST:event_Rutas1MouseEntered

    private void Rutas1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rutas1MouseExited
        reportes.setSize(0, 0);
        reportes2.setSize(0, 0);        // TODO add your handling code here:
    }//GEN-LAST:event_Rutas1MouseExited

    private void Rutas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rutas1ActionPerformed
        // TODO add your handling code here:
        TipoPersonal tp = null;
        if (ventanasAbiertas(tp)) {
            tp = new TipoPersonal();
            principal.add(tp);
            Dimension desktopSize = principal.getSize();
            Dimension internalSize = tp.getSize();
            tp.setLocation((desktopSize.width - internalSize.width) / 2, (desktopSize.height - internalSize.height) / 2);
            tp.setVisible(true);
        }
    }//GEN-LAST:event_Rutas1ActionPerformed

    private void reportes2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportes2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_reportes2MouseEntered

    private void reportes2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportes2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_reportes2MouseExited

    private void menuFacturacion1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFacturacion1MouseEntered
        // TODO add your handling code here:
        usuario.setSize(130,60);
    }//GEN-LAST:event_menuFacturacion1MouseEntered

    private void menuFacturacion1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFacturacion1MouseExited
        // TODO add your handling code here:
        usuario.setSize(0,0);
    }//GEN-LAST:event_menuFacturacion1MouseExited

    private void menuFacturacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFacturacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFacturacion1ActionPerformed

    private void fac3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fac3MouseEntered
        // TODO add your handling code here:
        usuario.setSize(130, 60);
    }//GEN-LAST:event_fac3MouseEntered

    private void fac3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fac3MouseExited
        // TODO add your handling code here:
        usuario.setSize(0,0);
    }//GEN-LAST:event_fac3MouseExited

    private void fac3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fac3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fac3ActionPerformed

    private void fac4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fac4MouseEntered
        // TODO add your handling code here:
        usuario.setSize(130, 60);
    }//GEN-LAST:event_fac4MouseEntered

    private void fac4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fac4MouseExited
        // TODO add your handling code here:
        usuario.setSize(0,0);
    }//GEN-LAST:event_fac4MouseExited

    private void fac4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fac4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fac4ActionPerformed

    private void usuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioMouseEntered

    private void fac4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fac4MouseClicked
        // TODO add your handling code here:
        cerrarSesion();
    }//GEN-LAST:event_fac4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimeraInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimeraInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimeraInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimeraInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buses;
    private javax.swing.JButton Clientes;
    private javax.swing.JButton Clientes1;
    private javax.swing.JButton Encomiendas;
    private javax.swing.JButton Encomiendas2;
    private javax.swing.JButton Encomiendas3;
    private javax.swing.JButton Encomiendas5;
    private javax.swing.JButton Encomiendas6;
    private javax.swing.JButton Rutas;
    private javax.swing.JButton Rutas1;
    private javax.swing.JButton Unidades;
    private javax.swing.JButton Viajes;
    private javax.swing.JButton empleados;
    public static javax.swing.JButton fac1;
    public static javax.swing.JButton fac3;
    public static javax.swing.JButton fac4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JButton menuFacturacion1;
    private javax.swing.JButton oficinas;
    public static javax.swing.JDesktopPane principal;
    private javax.swing.JPanel reportes;
    private javax.swing.JPanel reportes1;
    private javax.swing.JPanel reportes2;
    private javax.swing.JLabel txtUsuaio;
    public static javax.swing.JPanel usuario;
    // End of variables declaration//GEN-END:variables
}
